In [ ]:
from sklearn.datasets import make_classification

X, y = make_classification(
    n_samples=1000, 
    n_features=5, 
    n_informative=2, 
    n_classes=2, 
    random_state=888
)

In [ ]:
import pandas as pd


dataset = pd.DataFrame(X)

dataset.columns = ['X11', 'X22', 'X33', 'X44', 'X55']

dataset['y'] = y

dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   X11     1000 non-null   float64
 1   X22     1000 non-null   float64
 2   X33     1000 non-null   float64
 3   X44     1000 non-null   float64
 4   X55     1000 non-null   float64
 5   y       1000 non-null   int64
dtypes: float64(5), int64(1)
memory usage: 47.0 KB

In [ ]:
dataset['y'].value_counts()

1    502
0    498
Name: y, dtype: int64

In [ ]:
dataset.head()

        X11       X22       X33       X44       X55  y
0 -0.314410  0.874167 -1.078451  0.712641  0.982148  0
1  1.052601 -0.914855  0.990498 -0.527644  0.103189  1
2 -1.681751  0.086494  0.208451 -0.427190  0.491453  1
3  1.597060 -0.512908  0.363064  0.007788 -0.816214  1
4 -0.868158  0.611798 -0.631024  0.303333 -1.075730  0

In [ ]:

ros = RandomOverSampler()
X_ros, y_ros = ros.fit_resample(X, y)
print(Counter(y_ros))
Counter({1: 9847, 2: 9867})

Counter({0: 502, 1: 502})

Counter({1: 9847, 2: 9867})

In [ ]:

rus = RandomUnderSampler() 
X_rus, y_rus = rus.fit_resample(X, y)
print(Counter(y_rus))
Counter({1: 175, 0: 145})

Counter({0: 498, 1: 498})

Counter({1: 175, 0: 145})